config/routes.rb
Mywork::Application.routes.draw do
  get "store/index"

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '(:locale)' do

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  resources :products do
    get :who_bought, :on => :member
  end

    root :to => 'store#index', :as => 'store'

  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, :dependent => :destroy

  attr_accessible :quantity, :initial_quantity

  attr_reader :items

 

	def add_product(product_id)
    
         current_item = line_items.where(:product_id => product_id).first
             if current_item && current_item.product.initial_quantity.present?
               current_item.quantity += 1
               current_item.product.initial_quantity -= 1
               current_item.product.save
               
             else
               current_item = LineItem.new(:product_id=>product_id, :quantity => 1)
               current_item.product.initial_quantity -= 1
               current_item.product.save
               

               line_items << current_item
             end
               current_item
    end

    def total_price
        line_items.to_a.sum { |item| item.total_price }
    end

       def total_items
            line_items.sum(:quantity)
       end

       
  # attr_accessible :title, :body
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	skip_before_filter :authorize, :only => [:create, :update, :delete]

	def index
		@carts = Cart.all
	end

	def new
		@cart = Cart.new
	end

	def create
		@cart = Cart.new(params[:cart])
		if @cart.save
		   redirect_to carts_path
		else
			render action: "new"
		end
	end

	def show
		begin

		@cart = Cart.find(params[:id])
	    rescue ActiveRecord::RecordNotFound
	      logger.error "Attempt to access invalid cart #{params[:id]}"
	      redirect_to store_url, :notice => 'Invalid cart'
	    else
	      respond_to do |format|
	      	format.html
	      	format.xml {render :xml => @cart}
	      end
	    end


	end

	def destroy
		@cart = Cart.find(params[:id])
		@cart.destroy
		session[:cart_id] = nil

		respond_to do |format|
            format.html { redirect_to(store_url) }
            format.xml { head :ok }
        end

	end

	def edit
		@cart = Cart.find(params[:id])
	end

	def update
    	@cart = Cart.find(params[:id])
    	respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
        end
      end
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div class="cart_title"><%= t('.title') %></div>
<table>
<%= render(cart.line_items) %>
<tr class="total_line">
<td colspan="2">Total</td>
<td class="total_cell"><%= number_to_currency(cart.total_price) %></td>
</tr>
</table>
<%= button_to t('.checkout'), new_order_url, :method=>:get %>

<%= button_to t('.empty'), cart, :method => :delete,
:confirm => 'Are you sure?' %>

app/views/carts/edit.html.erb
<h1> Edit Cart </h1>
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Update Cart"%>
  </div>
<% end %>

app/views/carts/index.html.erb
<h1>Listing line_items</h1>
<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1> New Cart </h1>
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Create Cart"%>
  </div>
<% end %>

app/views/carts/show.html.erb
<% unless cart.line_items.empty? %>
<div class="cart_title">Your Cart</div>

<table>
<%= render(@cart.line_items) %>

<tr class="total_line">
<td colspan="2">Total</td>
<td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
</tr>
</table>


<%= button_to 'Empty cart', @cart, :method => :delete, :confirm => 'Are you sure?' %>
<% end %>