config/routes.rb
Mywork::Application.routes.draw do
  get "store/index"

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '(:locale)' do

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  resources :products do
    get :who_bought, :on => :member
  end

    root :to => 'store#index', :as => 'store'

  end

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :order
	belongs_to :product
    belongs_to :cart

  attr_accessible :cart_id, :product_id, :product, :quantity, :initial_quantity

  def total_price
      product.price * quantity
  end

   # def self.from_cart_item(cart_item)
   #   li = self.new
   #   li.product = cart_item.product
   #   li.quantity = cart_item.quantity
   #   li.total_price = cart_item.price
   #   li
   #  end


end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  skip_before_filter :authorize, :only => :create


	def index
		@line_items = LineItem.all
	end

	def new
		@line_item = LineItem.new
	end

	def show
		@line_item=LineItem.find(params[:id])
	end

	def create    
		@cart = current_cart
    @product = Product.find(params[:product_id])
    @line_item = @cart.add_product(@product.id)
    respond_to do |format|
      if @line_item.save
          format.json { render json: @line_item, status: :created, location: @line_item }
          format.js { @current_item = @line_item }
          format.html { redirect_to(store_url) }
          format.xml { render :xml => @line_item,
            :status => :created, :location => @line_item }
      else
          format.json { render json: @line_item.errors, status: :unprocessable_entity }
          format.html { render :action => "new" }
          format.xml { render :xml => @line_item.errors, :status => :unprocessable_entity }
      end
    end
	end

	def edit
		@line_item=LineItem.find(params[:id])
	end

	def destroy
		@line_item=LineItem.find(params[:id])
		@line_item.destroy
	    redirect_to line_item_path
	end

	def update
    	@line_item = LineItem.find(params[:id])
    	respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
        format.html { redirect_to @line_item, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
        end
      end
    end

end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
<tr id="current_item">
<% else %>
<tr>
<% end %>
<tr>
<td><%= line_item.quantity %>&times;</td>
<td><%= line_item.product.title %></td>
<td class="item_price"><%= number_to_currency(line_item.total_price) %></td>
</tr>

app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s",
            line_item.quantity,
            truncate(line_item.product.title, :length => 50)) %>

app/views/line_items/create.js.erb
// // alert('NO PROBLEM HERE');

 // $('#notice').each{ |notice| notice.hide }

//  $(document).ready(function(){
//    setTimeout(function(){
//       $("p.notice").hide("slow");
//    },1000);
// });



 $('#cart').html("<%= escape_javascript(render(@cart)) %>");

 $('#cart').css({ 'background-color': "#88ff88" }).animate({ 'background-color': "#114411" }, 4000);
  $("#<%= params[:product_id] %> span").html("<%= @product.initial_quantity %>");
// page.select("#notice" ).each { |notice| notice.hide }
//  page[:cart].visual_effect :blind_down if @cart.total_items == 1
// page[:current_item].visual_effect :highlight,
// :startcolor => "#88ff88" ,
// :endcolor => "#114411"

app/views/line_items/edit.html.erb
<h1> Update Line Item</h1>
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br />
    <%= f.number_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit "Update"%>
  </div>
<% end %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Cart</th>
  </tr>

<% @line_items.each do |line_item| %>
  <tr>
    <td><%= line_item.product_id %></td>
    <td><%= line_item.cart_id %></td>
    <td><%= link_to 'Show', line_item %></td>
    <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
    <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1> New Line Item </h1>
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br />
    <%= f.number_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @line_item.product_id %>
</p>

<p>
  <b>Cart:</b>
  <%= @line_item.cart_id %>
</p>


<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>